services:
  - type: web
    name: my-fastapi-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    build:
      environment:
        pythonVersion: 3.11.9
